# Generated by Django 3.0 on 2022-07-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20220708_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=10)),
                ('des', models.TextField(default='')),
                ('price', models.IntegerField()),
                ('img', models.ImageField(default='', upload_to='pro')),
                ('review', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
