# Generated by Django 3.0 on 2022-07-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20220708_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro',
            name='des',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pro',
            name='review',
            field=models.TextField(max_length=50),
        ),
    ]
